version: "3.1"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app/
    entrypoint: ["/bin/bash", "-c", "/usr/src/app/docker/start_app.sh"]
    ports:
      - "80:80"
    tty: true
    image: brooks-insurance-web
